### PR TITLE
Multiple accept attributes

### PR DESCRIPTION
**Pull request by tsibley**
Resolves https://rt.cpan.org/Ticket/Display.html?id=107786 and #1

### CODE REVIEW

**Comment by jjn1056** [comment]
Looks good, I'll try to get this merged up.  been a busy fall

**Comment by tsibley** [comment]
Thanks!

**Comment by tsibley** [comment]
@jjn1056 Ping?

**Comment by bbarker** [comment]
Any chance to see this merged? May be using the library more soon!

**Pull request merged**
